namespace Sopropl_Backend.Models
{
    public enum ActivityType
    {
        BUG, CHANGE_REQUEST, DEVELOPMENT, ENHANCEMENT, IDEA, MAINTENANCE, 
        QUALITY_ASSURANCE, RELEASE, RESEARCH, UNIT_TESTING, UPDATE, EPIC, STORY, OTHERS
    }
}